//
//  NetgearUITests.swift
//  NetgearUITests
//
//  Created by Cillian O'Keeffe on 14/07/2025.
//

import XCTest
@testable import Netgear

final class NetgearUITests: XCTestCase {
    
    // NOTE: I am disabling this test as I am getting an error when entering text:
    //
    // Failed to failed to scroll to visible (by AX action) Key, {{157.3, 931.0}, {39.3, 46.0}}, label: 'T', error: Error kAXErrorCannotComplete performing AXAction kAXScrollToVisibleAction on element AX element pid: 84720, elementOrHash.elementID: 105553151092496.56. (Underlying Error: Error kAXErrorCannotComplete performing AXAction kAXScrollToVisibleAction on element AX element pid: 84720, elementOrHash.elementID: 105553151092496.56)
    //
    // Seeing as the code is autogenerated by xcode, this is surprising.
    //
    func testSelectedBookUpdatesNavigationPath() {
        let app = XCUIApplication()
        app.activate()
        let booksBooksBooksStaticText = app/*@START_MENU_TOKEN@*/.staticTexts["Books Books Books"]/*[[".navigationBars",".staticTexts.firstMatch",".staticTexts[\"Books Books Books\"]"],[[[-1,2],[-1,0,1]],[[-1,2],[-1,1]]],[0]]@END_MENU_TOKEN@*/
        booksBooksBooksStaticText.tap()
        
        let searchForInformationStaticText = app/*@START_MENU_TOKEN@*/.staticTexts["Search for information on your favourite books via the Google Books API"]/*[[".otherElements.staticTexts[\"Search for information on your favourite books via the Google Books API\"]",".staticTexts[\"Search for information on your favourite books via the Google Books API\"]"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/
        searchForInformationStaticText.tap()
        
        let searchSearchField = app/*@START_MENU_TOKEN@*/.searchFields["Search"]/*[[".navigationBars.searchFields[\"Search\"]",".searchFields",".containing(.image, identifier: \"magnifyingglass\").firstMatch",".firstMatch",".searchFields[\"Search\"]"],[[[-1,4],[-1,1,1],[-1,0]],[[-1,3],[-1,2]]],[0]]@END_MENU_TOKEN@*/
        searchSearchField.tap()
        searchSearchField.tap()
        XCTAssertTrue(searchSearchField.waitForExistence(timeout: 5))
        app/*@START_MENU_TOKEN@*/.keys["T"]/*[[".otherElements.keys[\"T\"]",".keys[\"T\"]"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.keys["e"]/*[[".otherElements.keys[\"e\"]",".keys[\"e\"]"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.keys["s"]/*[[".otherElements.keys[\"s\"]",".keys[\"s\"]"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.keys["t"]/*[[".otherElements.keys[\"t\"]",".keys[\"t\"]"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.buttons["Search"]/*[[".otherElements",".buttons[\"search\"]",".buttons[\"Search\"]"],[[[-1,2],[-1,1],[-1,0,1]],[[-1,2],[-1,1]]],[0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.pageIndicators["page 1 of 10"]/*[[".otherElements.pageIndicators[\"page 1 of 10\"]",".pageIndicators.firstMatch",".pageIndicators[\"page 1 of 10\"]"],[[[-1,2],[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.pageIndicators["page 2 of 10"]/*[[".otherElements.pageIndicators[\"page 2 of 10\"]",".pageIndicators.firstMatch",".pageIndicators[\"page 2 of 10\"]"],[[[-1,2],[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.pageIndicators["page 3 of 10"]/*[[".otherElements.pageIndicators[\"page 3 of 10\"]",".pageIndicators.firstMatch",".pageIndicators[\"page 3 of 10\"]"],[[[-1,2],[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
        
        let element = app/*@START_MENU_TOKEN@*/.cells.images.firstMatch/*[[".images.element(boundBy: 1)",".cells.images.firstMatch"],[[[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/
        element.tap()
        app.otherElements.element(boundBy: 3).tap()
        
        let backButton = app/*@START_MENU_TOKEN@*/.buttons["Back"]/*[[".navigationBars.buttons[\"Back\"]",".buttons.firstMatch",".buttons[\"Back\"]"],[[[-1,2],[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/
        backButton.tap()
        app/*@START_MENU_TOKEN@*/.pageIndicators["page 4 of 10"]/*[[".otherElements.pageIndicators[\"page 4 of 10\"]",".pageIndicators.firstMatch",".pageIndicators[\"page 4 of 10\"]"],[[[-1,2],[-1,1],[-1,0]]],[0]]@END_MENU_TOKEN@*/.tap()
        element.tap()
        backButton.tap()
        app/*@START_MENU_TOKEN@*/.staticTexts["Cancel"]/*[[".buttons",".staticTexts.firstMatch",".staticTexts[\"Cancel\"]"],[[[-1,2],[-1,0,1]],[[-1,2],[-1,1]]],[0]]@END_MENU_TOKEN@*/.tap()
        searchForInformationStaticText.tap()
        booksBooksBooksStaticText.tap()
 
    }
}
